-- BU SCRIPT, MEVCUT VERİTABANI ŞEMASINI WEB SİTESİNİN BEKLENTİLERİNE GÖRE DÜZELTİR VE EKSİK TABLOLARI OLUŞTURUR.

-- 1. EKSİK OLAN 'PROFILES' TABLOSUNU OLUŞTUR (Supabase Auth ile uyumluluk için standart)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamp with time zone,
  username text UNIQUE,
  full_name text,
  avatar_url text,
  website text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_username_check CHECK (char_length(username) >= 3)
);

-- RLS (Row Level Security) açalım
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. TABLO İLİŞKİLERİ VE AUTO-INCREMENT (IDENTITY) DÜZELTMELERİ

-- Uretim Kayit Tablosu Düzeltmeleri
-- HATA: makine_id identity olmamalı, uretim_id identity olmalı.
ALTER TABLE public.uretim_kayit ALTER COLUMN makine_id DROP IDENTITY IF EXISTS; -- Önce yanlış identity'yi kaldır
ALTER TABLE public.uretim_kayit ALTER COLUMN uretim_id ADD GENERATED BY DEFAULT AS IDENTITY; -- Doğru identity'yi ekle
-- Sequence'i güncelle
SELECT setval(pg_get_serial_sequence('uretim_kayit', 'uretim_id'), COALESCE((SELECT MAX(uretim_id) FROM public.uretim_kayit), 0) + 1, false);


-- Siparis Tablosu Düzeltmeleri
ALTER TABLE public.siparis ALTER COLUMN siparis_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('siparis', 'siparis_id'), COALESCE((SELECT MAX(siparis_id) FROM public.siparis), 0) + 1, false);


-- Siparis Maliyet Tablosu Düzeltmeleri
ALTER TABLE public.siparis_maliyet ALTER COLUMN siparis_maliyet_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('siparis_maliyet', 'siparis_maliyet_id'), COALESCE((SELECT MAX(siparis_maliyet_id) FROM public.siparis_maliyet), 0) + 1, false);


-- Hammadde Tablosu Düzeltmeleri
ALTER TABLE public.hammadde ALTER COLUMN hammadde_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('hammadde', 'hammadde_id'), COALESCE((SELECT MAX(hammadde_id) FROM public.hammadde), 0) + 1, false);

-- Makine Tablosu Düzeltmeleri
ALTER TABLE public.makine ALTER COLUMN makine_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('makine', 'makine_id'), COALESCE((SELECT MAX(makine_id) FROM public.makine), 0) + 1, false);

-- Makine Arıza Tablosu Düzeltmeleri
ALTER TABLE public.makine_ariza ALTER COLUMN ariza_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('makine_ariza', 'ariza_id'), COALESCE((SELECT MAX(ariza_id) FROM public.makine_ariza), 0) + 1, false);

-- Makine Bakım Tablosu Düzeltmeleri
ALTER TABLE public.makine_bakim ALTER COLUMN bakim_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('makine_bakim', 'bakim_id'), COALESCE((SELECT MAX(bakim_id) FROM public.makine_bakim), 0) + 1, false);

-- Müşteriler Tablosu Düzeltmeleri
ALTER TABLE public.musteriler ALTER COLUMN musteri_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('musteriler', 'musteri_id'), COALESCE((SELECT MAX(musteri_id) FROM public.musteriler), 0) + 1, false);

-- Personel Tablosu Düzeltmeleri
ALTER TABLE public.personel ALTER COLUMN personel_id DROP DEFAULT; -- Önceki default 0'ı kaldır
ALTER TABLE public.personel ALTER COLUMN personel_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('personel', 'personel_id'), COALESCE((SELECT MAX(personel_id) FROM public.personel), 0) + 1, false);

-- Tedarikciler Tablosu Düzeltmeleri
ALTER TABLE public.tedarikciler ALTER COLUMN tedarikci_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tedarikciler', 'tedarikci_id'), COALESCE((SELECT MAX(tedarikci_id) FROM public.tedarikciler), 0) + 1, false);

-- Ürün Stok Tablosu Düzeltmeleri
ALTER TABLE public.urun_stok ALTER COLUMN urun_stok_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('urun_stok', 'urun_stok_id'), COALESCE((SELECT MAX(urun_stok_id) FROM public.urun_stok), 0) + 1, false);

-- 3. GEREKLİ İZİNLERİ VER (Uygulamanın çalışması için)
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 4. DATABASE GENEL AYARLARI (Gerekirse)
-- Timezone ayarı vs. buraya eklenebilir.
