
-- 1. STORAGE: BUCKET OLUŞTURMA
-- Storage schema'sına bucket ekliyoruz. public=true yaparak herkese açık yapıyoruz.
INSERT INTO storage.buckets (id, name, public) 
VALUES ('urun-dokumanlari', 'urun-dokumanlari', true) 
ON CONFLICT (id) DO UPDATE SET public = true;

-- Bucket erişim politikaları (Basitçe herkese açık yapıyoruz demo için)
-- Not: Storage politikalarını SQL ile yönetmek karmaşık olabilir, genellikle RLS ile yapılır.
-- Ancak bucket public=true olduğu için okuma sorunu olmayacaktır. Yazma için service_role veya policy gerekir.

-- 2. SCHEMA: PROFILES TABLOSU VE IDENTITY FIX
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamp with time zone,
  username text UNIQUE,
  full_name text,
  avatar_url text,
  website text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_username_check CHECK (char_length(username) >= 3)
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Identity Fixes (Mevcut verileri koruyarak identity ekle)
DO $$
DECLARE
    t text;
    pk text;
    has_identity boolean;
BEGIN
    FOR t, pk IN VALUES 
        ('uretim_kayit', 'uretim_id'),
        ('siparis', 'siparis_id'),
        ('siparis_maliyet', 'siparis_maliyet_id'),
        ('hammadde', 'hammadde_id'),
        ('makine', 'makine_id'),
        ('makine_ariza', 'ariza_id'),
        ('makine_bakim', 'bakim_id'),
        ('musteriler', 'musteri_id'),
        ('personel', 'personel_id'),
        ('tedarikciler', 'tedarikci_id'),
        ('urun_stok', 'urun_stok_id'),
        ('urun', 'urun_id')
    LOOP
        -- Check if column is already identity
        SELECT is_identity INTO has_identity 
        FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = t AND column_name = pk;

        IF NOT has_identity THEN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', t, pk);
        END IF;

        -- Update sequence
        EXECUTE format('SELECT setval(pg_get_serial_sequence(''%I'', ''%I''), COALESCE((SELECT MAX(%I) FROM public.%I), 0) + 1, false)', t, pk, pk, t);
    END LOOP;
END $$;

-- uretim_kayit makine_id identity fix
ALTER TABLE public.uretim_kayit ALTER COLUMN makine_id DROP IDENTITY IF EXISTS;

-- 3. DATA SEEDING (Önce temizle, sonra ekle)
-- Foreign Key constraintleri nedeniyle sıralama önemlidir.
-- Cascade truncate ile temizliyoruz.
TRUNCATE TABLE 
  public.siparis_maliyet, 
  public.siparis, 
  public.uretim_kayit, 
  public.urun_recetesi, 
  public.urun_stok, 
  public.hammadde_hareket, 
  public.makine_ariza, 
  public.makine_bakim, 
  public.hammadde, 
  public.makine, 
  public.urun, 
  public.musteriler, 
  public.tedarikciler, 
  public.personel 
RESTART IDENTITY CASCADE;

-- Insert Data (Buraya seed_data.sql içeriğinin tamamını kopyalıyoruz - tool kopyalayacak)
-- NOT: Kopyalama işlemini run_full_setup.js içinde concat yaparak halledeceğim, buraya sadece placeholder koymuyorum.
-- Bu dosya sadece şema ve bucket fixleri için temel olsun.
-- Data kısmını run_full_setup.js dosyasında seed_data.sql'den okuyup ekleyeceğim.
-- Part 1: Cleanup and Base Data
-- TABLES: Personel, Tedarikciler, Musteriler

-- Cleanup
TRUNCATE TABLE 
  public.siparis_maliyet, 
  public.siparis, 
  public.uretim_kayit, 
  public.urun_recetesi, 
  public.urun_stok, 
  public.hammadde_hareket, 
  public.makine_ariza, 
  public.makine_bakim, 
  public.hammadde, 
  public.makine, 
  public.urun, 
  public.musteriler, 
  public.tedarikciler, 
  public.personel 
RESTART IDENTITY CASCADE;

-- 1. PERSONEL
INSERT INTO public.personel (personel_id, ad, soyad, unvan, mail, sifre) VALUES
(3006, 'Arda', 'Ünal', 'Saha Montaj', null, null),
(3007, 'İbrahim', 'Şengün', 'Saha Montaj', null, null),
(3008, 'Yusuf', 'Hokkabaz', 'Saha Montaj', null, null),
(3010, 'Ahmet', 'Erli', 'Üretim Personeli', null, null),
(3005, 'Mustafa', 'Erten', 'Servis personeli ', '', null),
(3004, 'Ekrem', 'Ercan', 'Saha Montaj', '', null),
(3000, 'Salih', 'Şener', 'Şirket Sahibi', 'salihsener@yonetici.com', '123456'),
(3001, 'Yağız', 'Şener', 'Genel Müdür', 'yagizsener@yonetici.com', '123456'),
(3002, 'Muhammed Tahir', 'Tüzün', 'Muhasebe', 'mtahirtuzun@muhasebe.com', '123456'),
(3009, 'Zafer', 'Sezer', 'Üretim Şefi', 'zafersezer@uretimsefi.com', '123456'),
(3003, 'Murat', 'Karabıyık', 'Teknisyen', 'muratkarabiyik@teknisyen.com', '123456');

-- 2. TEDARIKCILER
INSERT INTO public.tedarikciler (tedarikci_id, firma, ad, soyad, cari_kodu, telefon, il, ilce, adres, grubu, aktif) VALUES
(1111, 'MAKTEK', 'ALİ ', 'KURNAZ', 'CR00011', '232 328 2106', null, null, null, 'SATICILAR', 'Evet'),
(1112, 'CELİLSAN', 'DELAL', 'ŞAM', 'CR00013', '232 365 0901', 'İZMİR', 'BAYRAKLI', null, 'SATICILAR', 'Evet'),
(1113, 'TESA', 'İCLAL', 'BAYRAK', 'CR00014', '232 449 6565', null, null, null, 'SATICILAR', 'Evet'),
(1114, 'GENTA', 'İRKRA', 'ÇALIŞKAN', 'CR00018', '216 452 9501', null, null, null, 'SATICILAR', 'Evet'),
(1115, 'STAR POMPA', 'GÜLAY', 'KURT', 'CR00029', '212 501 5370', 'İSTANBUL', 'EYÜP', null, 'SATICILAR', 'Evet'),
(1116, 'DİNAMİK ISI', 'ŞEVVAL', 'AYŞE', 'CR00030', null, null, null, null, 'SATICILAR', 'Evet'),
(1117, 'ELTERM', 'CEYDA', 'ÜNAL', 'CR00031', '232 449 7673', 'İZMİR', 'KONAK ', null, 'SATICILAR', 'Evet'),
(1118, 'YAŞAM PROJE', 'İRKA', 'BAŞ', 'CR00039', null, null, null, null, 'SATICILAR', 'Evet'),
(1119, 'TERMAK', 'İRFAN', 'KOL', 'CR00061', null, null, null, null, 'SATICILAR', 'Evet'),
(1120, 'ER POMPA', 'ŞULE', 'KOCA', 'CR00062', null, null, null, null, 'SATICILAR', 'Evet'),
(1121, 'EGEMAK', 'ESLEM', 'TÜRK', 'CR00067', '232 458 1227', 'İZMİR', 'KONAK', null, 'SATICILAR', 'Evet'),
(1122, 'GÜRTEKNİK', 'CEVDET', 'BALA', 'CR00072', null, null, null, null, 'SATICILAR', 'Evet'),
(1123, 'TEZKO', 'UMUT', 'YAN', 'CR00085', null, null, null, null, 'SATICILAR', 'Evet'),
(1124, 'AKANTEL', 'KÜBRA', 'BACAK', 'CR00098', null, null, null, null, 'SATICILAR', 'Evet'),
(1125, 'TERPA TEKNİK', 'SAMET', 'OCAK', 'CR00109', '232 459 4731', null, null, null, 'SATICILAR', 'Evet'),
(1126, 'YAĞMUR TEKNİK', 'TARIK', 'DEMİRGİL', 'CR00122', null, null, null, null, 'SATICILAR', 'Evet'),
(1127, 'GÜR MÜHENDİSLİK', 'TURGUT', 'AYGÜL', 'CR00145', '232 433 34 25', 'İZMİR', 'YENİŞEHİR', 'EGE TİC.MERK. 1203/3SK NO:5/B', 'SATICILAR', 'Evet'),
(1128, 'HİVAC', 'HEVVAL', 'AKGÜN', 'CR00165', '232 433 3550', null, null, null, 'SATICILAR', 'Evet'),
(1129, 'ALP POMPA', 'BEYZA', 'YAVUZ', 'CR00202', null, null, null, null, 'SATICILAR', 'Evet'),
(1130, 'TERMOMAK', 'YAĞIZ', 'KOÇAK', 'CR00205', '232', null, null, null, 'SATICILAR', 'Evet'),
(1131, 'ISIPARK', 'BADE', 'GÜNEŞ', 'CR00223', '232 457 9902', null, null, null, 'SATICILAR', 'Evet'),
(1132, 'ZEYBEKLER TOTEM', 'BERRA', 'ESEN', 'CR00299', '246 224 3240', null, null, null, 'SATICILAR', 'Evet'),
(1133, 'ERDENER ', 'LALE', 'GÜL', 'CRV00207', '266 373 27 51', null, null, null, 'SATICILAR', 'Evet'),
(1134, 'YAPIMAR', 'VARAN', 'AKTÜRK', 'CRV00279', '232 433 3900', null, null, null, 'SATICILAR', 'Evet'),
(1135, 'DUYAR MOTOR POMPA', 'MEVRA', 'ERASLAN', 'CRV00300', '232 449 1646', null, null, null, 'SATICILAR', 'Evet'),
(1136, 'İZBOY KİMYASAL ÜRÜNLER BOYA FİLTRE ve DANIŞMANLIK TİC.LTD.ŞTİ.', 'HAVVA', 'KALLA', 'CRV00397', '232 436 5 436', 'İZMİR', 'BORNOVA', 'EGEMENLİK MH. 6138 SK. NO:34 IŞIKKENT', 'SATICILAR', 'Evet'),
(1137, 'STARTEK', 'ALEV', 'HANCI', 'CRV00486', '232 462 3511', 'İZMİR', 'KONAK', null, 'SATICILAR', 'Evet'),
(1138, 'SMYRNA ISITMA SOĞUTMA', 'SAMET', 'YEŞİLDUMAN', 'CRV00598', '232 433 31 68', 'İZMİR', 'KONAK', null, 'SATICILAR', 'Evet'),
(1139, 'BURSAM YAPI MLZ. TOPTAN DAĞITIM TİC.SAN.LTD.ŞTİ.', 'EREN', 'DUMANCI', 'CRV00658', '224 211 0909', null, null, null, 'SATICILAR', 'Evet'),
(1140, 'NORTEK POMPA', 'ERVA', 'ŞAM', 'CRV00660', '232 457 5011', 'İZMİR', null, null, 'SATICILAR', 'Evet'),
(1141, 'TİMPAŞ ISITMA SOĞUTMA SİST. A.Ş.', 'ŞANLI', 'YAR', 'CRV00870', '232 459 4004', 'İZMİR', 'BORNOVA ', 'YUNUS EMRE MAH. 7513/2 SOK.NO:2 E PINARBAŞI ', 'SATICILAR', 'Evet'),
(1142, 'AYDINLAR METAL A.Ş.', 'ALİYE', 'GÜNEŞ', 'CRV00911', '533 385 2430', null, null, null, 'SATICILAR', 'Evet'),
(1143, 'BATI GRUP', 'FIRAT', 'EKİCİ', 'CRV00968', '232 342 2266', null, null, null, 'SATICILAR', 'Evet'),
(1144, 'ÜNMAK', 'HASAN', 'CANKİ', 'CRV01000', '0246 224 3400', null, null, null, 'SATICILAR', 'Evet'),
(1145, 'EGEPA ISITMA SİST.', 'HÜSEYİN', 'ÜRKMEZ', 'CRV01120', null, null, null, null, 'SATICILAR', 'Evet'),
(1146, 'ZİRVETAŞ HIRDAVAT LTD. ŞTİ.', 'FATMA', 'ERTUĞRUL', 'CRV01173', '232 459 2042', 'İZMİR', 'YENİŞEHİR ', '1203 SK. NO:10/B', 'SATICILAR', 'Evet'),
(1147, 'BAHÇIVAN MOTOR', 'ALİ', 'ÜRESİN', 'CRV01283', '212 771 4848', 'İSTANBUL', 'ARNAVUTKÖY', null, 'SATICILAR', 'Evet'),
(1148, 'AYAZ TİCARET', 'KAZIM', 'DEMİRGİL', 'CRV01547', '373 2359', 'BALIKESİR', 'EDREMİT', 'HAMİDİYE MAH.SANAYİ SİTESİ NO:21', 'SATICILAR', 'Evet'),
(1149, 'MUGUL ELEKTRONİK', 'EYÜL', 'DUMAN', 'CRV01643', null, null, null, null, 'SATICILAR', 'Evet'),
(1150, 'SANPA', 'ESLEM', 'EGE', 'CRV01670', null, null, null, null, 'SATICILAR', 'Evet'),
(1151, 'ASYA PAN 3A ISITMA SOĞUTMA SİS. VE İNŞ. MALZ. PAZ. TİC.', 'İSMAİL', 'AÇIKBAŞ', 'CRV01679', '232 461 5007', 'İZMİR', 'BORNOVA', '4033 SOKAK NO:11 YEŞİLOVA', 'SATICILAR', 'Evet'),
(1152, 'NAKLİYECİ TAHİR', 'EGE', 'TUNAL', 'CRV01683', null, null, null, null, 'SATICILAR', 'Evet'),
(1153, 'AKNUR', 'EFE', 'BOYLAR', 'CRV01723', null, null, null, null, 'SATICILAR', 'Evet'),
(1154, 'İZFER', 'RÜMEYSA', 'ERASLAN', 'CRV01724', null, null, null, null, 'SATICILAR', 'Evet'),
(1155, 'İKOMAK', 'VOLKAN', 'TER', 'CRV01725', '232 457 7797', null, null, null, 'SATICILAR', 'Evet'),
(1156, 'DOĞGÜN YALITIM- YÜCEL DOĞGÜN', 'CIVAN ', 'VAROL', 'CRV01800', '322 346 0060', null, 'ADANA', null, 'SATICILAR', 'Evet'),
(1157, 'KATRE ISI SAN.TİC.A.Ş.', 'KEREM', 'BOZ', 'CRV01881', '212 415 4815', 'BALIKESİR', 'ALTIEYLÜL', null, 'SATICILAR', 'Evet'),
(1158, 'ELEKTRİKÇİ UFUK', 'YAĞMUR ', 'ERTÜRK', 'CRV01949', '507 589 4043', null, null, null, 'SATICILAR', 'Evet'),
(1159, 'Pİ AMBALAJ YALITIM LTD. ŞTİ.', 'KADRİ', 'BACAK', 'CRV01975', '232 220 0072', 'İZMİR', 'BORNOVA', 'EGEMENLİK MAHALLESİ 6106/35 SOK. NO:2/B IŞIKKENT', 'SATICILAR', 'Evet'),
(1160, 'HİDROTANK LTD. ŞTİ.', 'ELMAS', 'KESER', 'CRV02010', '216 508 1212', null, 'İSTANBUL', null, 'SATICILAR', 'Evet'),
(1161, 'SOLİMPEKS', 'ŞULE', 'ILGIZ', 'CRV02035', '530 100 6979', null, null, null, 'SATICILAR', 'Evet'),
(1162, 'GLOBAL WATER SOLUTIOS TİC.LTD.ŞTİ.', 'GAMZE', 'KURTULUŞ', 'CRV02041', null, null, null, null, 'SATICILAR', 'Evet'),
(1163, 'ÖZGÜR TESİSAT', 'ÜNAL ', 'KAYA', 'CRV02120', '396 6913', 'BALIKESİR', 'ALTINOLUK', null, 'SATICILAR', 'Evet'),
(1164, 'ERF GRUP MAKİNA İMALAT İHRACAT İTHALAT LTD. ŞTİ', 'UFUK', 'KORKMAZ', 'CRV02269', '212 494 4617', 'İSTANBUL', 'KÜÇÜKÇEKMECE', 'İKİTELLİ OSB MARMARA SAN SİT. N BLOK NO :17', 'SATICILAR', 'Evet'),
(1165, 'SEREN KLİMA', 'FİKRİ', 'DEMET', 'CRV02292', '533 567 8335', null, null, null, 'SATICILAR', 'Evet'),
(1166, 'VERİMLİ ENERJİ SİSTEMLERİ SAN.TİC.LTD.ŞTİ', 'EBRAR', 'EVGAR', 'CRV02370', '216 510 11 40', 'İSTANBUL', 'ATAŞEHİR', 'FERHATPAŞA MAH.AKDAL SK. NO:7 ATAŞEHİR/İSTANBUL', 'SATICILAR', 'Evet'),
(1167, 'KARESİ KAYNAK', 'BURAK', 'KUT', 'CRV02458', null, null, 'BALIKESİR', null, 'SATICILAR', 'Evet'),
(1168, 'ERNA METAL', 'LERZA', 'MUTLU', 'CRV02489', '412 5704', 'BALIKESİR', 'BURHANİYE', null, 'SATICILAR', 'Evet'),
(1169, 'YUSUF AKTAŞ', 'SEÇİL', 'ERZAN', 'CRV02590', '537 354 6636', null, null, null, 'SATICILAR', 'Evet'),
(1170, 'TESİSATÇI ONUR', 'NİL', 'CANDAN', 'CRV02604', '536 706 2724', null, null, null, 'SATICILAR', 'Evet'),
(1171, 'ARSLAN BOBİNAJ', 'NİHAT', 'ERASLAN', 'CRV02638', '0266 373 6383', null, null, 'EDREMİT', 'SATICILAR', 'Evet'),
(1172, 'ÇELMAK ÇELİK PASLANMAZ BORU SAN.VE TİC.A.Ş.', 'CAN', 'POLAT', 'CRV02642', '232 433 7049', 'İZMİR', 'KONAK', '1.SANAYİ SİTESİ 2825 SK.NO:32  35110   ', 'SATICILAR', 'Evet'),
(1173, 'DEMSAN LTD.ŞTİ.', 'PERVİZ', 'UZUN', 'CRV02675', '0212 549 63 23', null, null, null, 'SATICILAR', 'Evet');

-- 3. MUSTERILER
INSERT INTO public.musteriler (musteri_id, isim, soyisim, cari_kodu, telefon, il, ilce, adres, aktif) VALUES
(8000, 'FERİT', 'GEZGİN', 'CR00002', '505 803 2674', 'BALIKESİR', 'EDREMİT', 'Akçay', 'Evet'),
(8001, 'HÜSEYİN', 'YILMAZ', 'CR00003', '532 266 3274', 'BALIKESİR', 'EDREMİT', 'GÜRE İSKELESİ', 'Evet'),
(8002, 'SAVCI', 'ERDOĞAN', 'CR00004', '266 384 1089', 'BALIKESİR', 'EDREMİT', '532 648 3545 YAKICI DORUK VİLLA ORUÇ REİS CAD. AKÇAY', 'Evet'),
(8003, 'İZZET', 'CEYHAN', 'CR00005', '535 263 5135', 'BALIKESİR', 'EDREMİT', 'TURGUT REİS CAD. NO:64 2.DAİRE', 'Evet'),
(8004, 'AHMET', 'ŞENOL', 'CR00006', '532 470 9993', 'BALIKESİR', 'EDREMİT', 'GÜRE İSKELESİ', 'Evet'),
(8005, 'ŞÜKRÜ', 'ÇAY', 'CR00007', '533 213 1639', 'BALIKESİR', 'EDREMİT', 'GÜRE İSKELESİ', 'Evet'),
(8006, 'METİN', 'ÇELİK', 'CR00008', '266 384 1431', 'BALIKESİR', 'AYVALIK', '150 EVLER MAHALLESİ ', 'Evet'),
(8007, 'MENDERES', 'ŞAFAKGİLLER', 'CR00009', '266 392 1490', 'BALIKESİR', 'EDREMİT', 'ORGANİZE SANAYİ SİTESİ 392 1490', 'Evet'),
(8008, 'SÜLEYMAN', 'KOCAER', 'CR00010', '532 673 9308 ', 'BALIKESİR', 'EDREMİT', 'DALYAN MAH. ATATÜRK BUL NO:47  532 673 9308   ZEYTİNLİ', 'Evet'),
(8009, 'EMİN', 'ERDEM', 'CR00012', '546 599 7247', 'ÇANAKKALE', 'YENİCE', 'CUMHURİYET MAHALLESİ ', 'Evet'),
(8010, 'CENNET', 'KONUTLARI', 'CR00015', '542 517 2357', 'BALIKESİR', 'EDREMİT', 'ZEMİRHAN USTA 507 243 7643', 'Evet'),
(8011, 'METİN', 'YILDIZ', 'CR00016', '532 332 0851', 'BALIKESİR', 'BURHANİYE ', 'İSKELE MAH.KORDONBOYU CAD. NO:181', 'Evet'),
(8012, 'FAHRİ', 'GÜLAY', 'CR00017', 'CEMAL ERDEN', 'BALIKESİR', 'BURHANİYE', 'CUMHURİYET MAHALLESİ ', 'Evet'),
(8013, 'HÜNNAP', 'KURT', 'CR00019', '286 752 6581', 'ÇANAKKALE', 'AYVACIK', ' ALTUĞ BEY OTEL MD. OTEL NO - 286 752 6581 ADATEPE KÖYÜ vural  533 377 4482', 'Evet'),
(8014, 'MURAT', 'TUNA', 'CR00020', '532 374 3065', 'BALIKESİR', 'EDREMİT', 'KADIKÖY MAHALLESİ', 'Evet'),
(8015, 'MUSTAFA', 'KORKMAZ', 'CR00021', '544 845 8627', 'ÇANAKKALE', 'AYVACIK', 'NEVRUZ KÖYÜ', 'Evet'),
(8016, 'SULTAN', 'KENT', 'CR00022', '543 897 5281', 'BALIKESİR', 'EDREMİT', 'ÇAMLIBEL KÖYÜ GÜRE', 'Evet'),
(8017, 'ÖMER', 'ARIKAN', 'CR00023', '532 382 9095', 'BALIKESİR', 'AKÇAY', 'çakmak kent akçay', 'Evet'),
(8018, 'EMİN', 'BİÇER', 'CR00024', '533 958 5538', 'BALIKESİR', 'EDREMİT', 'K.KUYU', 'Evet'),
(8019, 'ŞENOL', 'ERKİN', 'CR00025', '533 446 2469', 'BALIKESİR', 'AKÇAY', 'AKÇAY', 'Evet'),
(8020, 'HALİL', 'PEHLİVAN', 'CR00027', '544 330 1710', 'BALIKESİR', 'EDREMİT', 'ÇAMLIBEL KÖYÜ GÜRE', 'Evet'),
(8021, 'AHMET', 'EROL', 'CR00028', '532 624 0927', 'BALIKESİR', 'EDREMİT', 'AVCILAR ', 'Evet'),
(8022, 'EMRE', 'PELVAN', 'CR00032', '532 768 0824', 'BALIKESİR', 'EDREMİT', 'GÜRE İSKELESİ', 'Evet'),
(8023, 'GAMZE', 'BİLGE', 'CR00033', '373 2709', 'BALIKESİR', 'EDREMİT', ' ÇAMLIBEL KÖYÜ', 'Evet'),
(8024, 'HÜSEYİN', 'ÇEVİK', 'CR00034', '538 313 8106', 'BALIKESİR', 'EDREMİT', 'GEZER APT. 538 313 8106', 'Evet'),
(8025, 'ALİ', 'LATİFOĞLU', 'CR00036', '532 764 9866', 'BALIKESİR', 'EDREMİT', '307SK NO:20  FATİH APT. AKÇAY', 'Evet'),
(8026, 'KAHRAMAN', 'DEMİR', 'CR00037', '533 708 9229', 'BALIKESİR', 'EDREMİT', 'YAKAMOZ YAKICI 545 674 1975', 'Evet'),
(8027, 'ŞAKİR', 'FENERLİ', 'CR00038', '286 618 1791', 'ÇANAKKALE', 'EZİNE', 'EZİNE', 'Evet'),
(8028, 'BAHŞİ', 'ÇELİK', 'CR00040', '533 483 1576', 'BALIKESİR', 'EDREMİT', 'ALTINKUM', 'Evet'),
(8029, 'HÜSEYİN', 'ATAR', 'CR00041', '530 519 6911 ', 'BALIKESİR', 'EDREMİT', 'BARAJ CD. NO:36', 'Evet'),
(8030, 'MEHMET', 'ÇİFÇİ', 'CR00042', '532 214 0428', 'MANİSA', 'SOMA', 'SOMA', 'Evet'),
(8031, 'ÖNGEN', 'AKYÜZ', 'CR00043', '286 752 2434-35', 'BALIKESİR', 'EDREMİT', 'ÇAMCI', 'Evet'),
(8032, 'ALİ', 'OĞUZ', 'CR00044', '532 387 1714', 'BALIKESİR', 'EDREMİT', 'İKİZÇAY MAHALLESİ .202 SOKAK ', 'Evet'),
(8033, 'METİN', 'ŞİMŞEK', 'CR00045', '532 578 0211', 'BALIKESİR', 'EDREMİT', 'SARIKIZ APT. 532 578 0211', 'Evet'),
(8034, 'MİNE', 'LALE', 'CR00046', '532 899 4235', 'BALIKESİR', 'EDREMİT', '(HALKBANKASI) 536 888 4743', 'Evet'),
(8035, 'AHMET', 'AMCA', 'CR00047', '538 097 9985', 'BALIKESİR', 'EDREMİT', 'AKÇAY 384 5261 - 539 588 1236', 'Evet'),
(8036, 'MUAMMER', 'TEKER', 'CR00048', '266 384 5261', 'BALIKESİR', 'EDREMİT', 'AKÇAY 384 5261 - 539 588 1236', 'Evet'),
(8037, 'ŞENER', 'BERBER', 'CR00049', '266 831 5120', 'BALIKESİR ', 'AYVALIK', 'ALİ ÇETİNKAYA MAHALLESİ ', 'Evet'),
(8038, 'FERİT', 'GÜLAY', 'CR00050', '542 663 8010', 'BALIKESİR', 'HAVRAN', 'BÜYÜKŞAPÇI', 'Evet'),
(8039, 'CEMAL', 'ÇAPAN', 'CR00051', '544 234 6017', 'BALIKESİR ', 'EDREMİT', 'ÇAMLIBEL KÖYÜ GÜRE', 'Evet'),
(8040, 'AYŞE', 'PAZAR', 'CR00052', '532 384 0401', 'BALIKESİR ', 'HAVRAN', 'HAMAMBAŞI', 'Evet'),
(8041, 'AHMET', 'UÇAR', 'CR00053', '551 111 6260', 'BALIKESİR', 'EDREMİT', 'KÜÇÜKKUYU', 'Evet'),
(8042, 'UMUT', 'ÇAVUR', 'CR00054', '536 850 5491', 'BALIKESİR', 'EDREMİT', 'KÜÇÜKKÖY YÖNETİCİLER SİTESİ  EDREMİT', 'Evet'),
(8043, 'HÜSEYİN', 'KAVLAKOĞLU', 'CR00055', '535 776 6367', 'BALIKESİR ', 'EDREMİT', 'AVCILAR 535 776 6367', 'Evet'),
(8044, 'MURAT', 'YILDIZ', 'CR00056', '535 666 4514', 'ÇANAKKALE', 'EZİNE', 'CAMİKEBİR MAHALLESİ 189.SOKAK CEMİLLER APT.', 'Evet'),
(8045, 'TUNCEL', 'ERYILDIRIM', 'CR00057', '537 351 4952', 'BALIKESİR', 'AKÇAY', 'ALAKOÇ MOTEL ARKASI 223 SOK. NO:4   ', 'Evet'),
(8046, 'ELİF', 'ISPARTA', 'CR00058', '555 433 0415', 'BALIKESİR', 'EDREMİT', 'GÜRE İSKELESİ', 'Evet'),
(8047, 'ALİ', 'SARIÇAM', 'CR00060', '537 308 7452', 'BALIKESİR', 'HAVRAN', 'EVCİLER APT.', 'Evet'),
(8048, 'CELAL', 'SİDAR', 'CR00063', '538 723 2290', 'ÇANAKKALE', 'AYVACIK', 'BEHRAMKALE', 'Evet'),
(8049, 'NAVİR', 'ALKAYA', 'CR00064', '535 729 1845', 'BALIKESİR', 'BURHANİYE', 'İSKELE MAH.KORDON BOYU CAD.NO:39 D:2 ÖREN', 'Evet'),
(8050, 'MUSA', 'SAKALLI', 'CR00065', '536 325 9288', 'BALIKESİR', 'EDREMİT', 'ALTINOLUK', 'Evet'),
(8051, 'YENİCE', 'YURT', 'CR00066', '547 899 2798', 'BALIKESİR', 'BURHANİYE ', 'HÜRRİYET CAD.NO:104', 'Evet'),
(8052, 'AHMET', 'BACAK', 'CR00068', '505 887 9552', 'BALIKESİR', 'HAVRAN', 'UMUT APT.', 'Evet'),
(8053, 'AHMET', 'KÖSE', 'CR00069', '539 454 0032', 'BALIKESİR', 'BURHANİYE', 'ALİ KEMAL DEVECİLER BULVARI NO:99', 'Evet'),
(8054, 'MEHMET', 'ERTAŞ', 'CR00070', '266 384 6943', 'BALIKESİR', 'ZEYTİNLİ', '542 697 9377 HALİL YAKICI 384 6943       ZEYTİNLİ HAKKI 532 661 4241', 'Evet'),
(8055, 'ÖNDER', 'GÜNGÖR', 'CR00071', '535 736 9483', 'ÇANAKKALE', 'AYVACIK', 'EVCİLER APT.', 'Evet'),
(8056, 'MEHMET', 'DEMİR', 'CR00073', '373 1678', 'BALIKESİR', 'EDREMİT', 'YENİ MAHALLE', 'Evet'),
(8057, 'MUSTAFA', 'İPEK', 'CR00074', '373 4263', 'BALIKESİR', 'HAVRAN', 'EVCİLER APT.', 'Evet'),
(8058, 'MEHMET', 'İŞİ', 'CR00075', '533 811 7434', 'BALIKESİR', 'EDREMİT', 'ÖREN MAH. ALTINYOL CAD. NO:9', 'Evet'),
(8059, 'ÖZER', 'GÜMÜŞ', 'CR00076', '532 343 9222', 'ÇANAKKALE', 'AYVACIK', 'UMUT APT.', 'Evet'),
(8060, 'EROL', 'KÖPRÜCÜ', 'CR00077', '532 777 4704', 'ÇANAKKALE', 'AYVACIK', 'EVCİLER APT.', 'Evet'),
(8061, 'MURAT', 'KÜÇÜKÇAKIR', 'CR00078', '542 626 8085', 'BALIKESİR', 'BURHANİYE', 'UMUT APT.', 'Evet'),
(8062, 'KADİR', 'BÖLEK', 'CR00079', '536 636 2367', 'BALIKESİR', 'BURHANİYE', 'UMUT APT.', 'Evet');
-- Part 2: Machines, Products, Raw Materials
-- TABLES: Makine, Makine_Ariza, Makine_Bakim, Urun, Urun_Stok, Hammadde

-- 4. MAKINE
INSERT INTO public.makine (makine_id, ad, tur, kapasite, toplam_calisma_saati) VALUES
(5500, 'CNC Router', 'Şekillendirme', '8 saat', 2250),
(5504, 'TIG Kaynak Makinesi', 'Kaynak (krom/çelik)', 'yok', 1250),
(5501, 'Lazer Kesim Makinesi', 'Sac kesim', '20 mm sac kalınlığına kadar kesim', 2000),
(5502, 'Hidrolik Pres', 'Şekillendirme', '200 ton baskı gücü', 1750),
(5503, 'MIG/MAG Kaynak Makinesi', 'Kaynak', '10 mm sac kalınlığına kadar kaynak', 1500),
(5505, 'Punta Kaynak Makinesi', 'İnce sac kaynağı', '3 mm sac kalınlığına kadar', 1000),
(5506, 'Taşlama/Polisaj Makinesi', 'Yüzey işleme', '5-10 parçalık yüzey işleme kapasitesi/gün', 800),
(5507, 'Boyama/Kaplama Sistemi', 'Koruma ve estetik', '50-100 m yüzey/gün', 1000),
(5508, 'Montaj Hattı', 'Birleştirme', '20-30 cihaz/gün (klima/ısı pompası)', 1750),
(5509, 'Basınç Test Cihazı', 'Dayanıklılık testi', '10-15 tank/kazan test/gün', 650),
(5510, 'Sızdırmazlık Test Sistemi', 'Kaçak kontrolü', '5-10 tank/kazan test/gün', 550),
(5511, 'Elektriksel Test Cihazı', 'Devre kontrolü', '20ü30 cihaz devre kontrol/gün', 750);

-- 5. MAKINE ARIZA
INSERT INTO public.makine_ariza (ariza_id, makine_id, personel_id, maliyet, ariza_turu) VALUES
(6003, 5503, 3006, 9, 'Tel besleme sorunu'),
(6002, 5502, 3004, 14, 'Hidrolik sızdırma'),
(6004, 5504, 3007, 8.5, 'Elektrot yanması'),
(6006, 5506, 3008, 5, 'Motor rulman arızası'),
(6007, 5507, 3004, 7.5, 'Nozul tıkanması'),
(6009, 5509, 3008, 4.5, 'Sensör hatası'),
(6011, 5511, 3003, 6.5, 'Devre kartı yanması'),
(6001, 5501, 3007, 22, 'Lazer tüp arızası'),
(6010, 5510, 3004, 4, 'Basınç pompası arızası'),
(6005, 5505, 3003, 6, 'Elektrot başı deformasyonu'),
(6008, 5508, 3006, 12, 'Konveyör bant kopması'),
(6000, 5500, 3003, 18, 'Mil arınması');

-- 6. MAKINE BAKIM
INSERT INTO public.makine_bakim (bakim_id, makine_id, bakim_tarihi, bakim_turu, maliyet) VALUES
(5800, 5500, '2025-02-01', 'Periyodik', 12),
(5802, 5502, '2025-01-04', 'Periyodik', 10),
(5804, 5504, '2025-01-04', 'Periyodik', 9),
(5805, 5505, '2025-01-04', 'Periyodik', 6),
(5806, 5506, '2025-01-04', 'Periyodik', 5),
(5808, 5508, '2025-01-04', 'Periyodik', 11),
(5809, 5509, '2025-01-04', 'Periyodik', 4.5),
(5810, 5510, '2025-01-04', 'Periyodik', 4),
(5811, 5511, '2025-01-04', 'Periyodik', 5.5),
(5801, 5501, '2025-01-04', 'Periyodik + Arıza', 15),
(5803, 5503, '2025-01-04', 'Arıza sonrası', 8),
(5807, 5507, '2025-01-04', 'Arıza sonrası', 7.5);

-- 7. URUN
INSERT INTO public.urun (urun_id, ad, tur, satis_fiyati) VALUES
(3013, 'klima sistemleri', 'konut', 35000),
(3012, 'ısı pompaları', 'konut', 90000),
(3014, 'merkezi sistem ısıtma cihazları', 'endüstriyel', 1000000),
(3015, 'kalorifer kazanları', 'konut', 140000),
(3016, 'yağ tankları (krom ve çelik)', 'endüstriyel', 450000);

-- 8. URUN STOK
INSERT INTO public.urun_stok (urun_stok_id, urun_id, miktar, son_guncelleme) VALUES
(3500, 3012, 45, '2025-10-26'),
(3501, 3013, 66, '2025-09-15'),
(3502, 3014, 28, '2025-11-16'),
(3503, 3015, 35, '2025-10-22'),
(3504, 3016, 41, '2025-07-10');

-- 9. HAMMADDE
INSERT INTO public.hammadde (hammadde_id, stok_adi, satis_fiyati, alis_fiyati, kalan_miktar, birim, kdv_satis, kdv_alis, grubu, ara_grubu, aktif, bilgi_kodu, kritik_stok, tedarikci_id) VALUES
(2113, ' GENLEŞME TANKI 500 LT.', '3.000,00', '1.982,00', '0', 'ADET', 20, 20, 'GENLEŞME TANKI', ' ', 'Evet', 435, '1', 1113),
(2114, ' GENLEŞME TANKI 100 LT.', '600', '370', '0', 'ADET', 20, 20, 'GENLEŞME TANKI', ' ', 'Evet', 436, '1', 1114),
(2115, ' GENLEŞME TANKI 200 LT.', '1.150,00', '700', '0', 'ADET', 20, 20, 'GENLEŞME TANKI', ' ', 'Evet', 437, '1', 1115),
(2117, ' 500-1500 PANSAN HAVLUPAN BEYAZ ', '150', '106,2', '0', 'ADET', 20, 20, 'HAVLUPAN', null, 'Evet', 2247, '1', 1117),
(2118, ' ETNA HİDROFOR 10/S7-22 ', '9.000,00', '6.870,00', '0', 'ADET', 20, 20, 'HİDROFOR', null, 'Evet', 2250, '0', 1118),
(2119, ' GENLEŞME TANKI CRUMA SİLİNDİR 24 LT.', '150', '95', '0', 'ADET', 20, 20, 'GENLEŞME TANKI', null, 'Evet', 2251, '1', 1119),
(2120, ' GENLEŞME TANKI CRUMA DİK 24 LT.', '300', '230', '0', 'ADET', 20, 20, 'GENLEŞME TANKI', null, 'Evet', 2252, '1', 1120),
(2022, ' 17*2 MM SANAYİ BORUSU', '30', '20', '72', 'MT', 20, 20, 'KAZAN MALZEMELERİ', 'BORU', 'Evet', 2254, '30', 1122),
(2023, ' 3,25*350 ELEKTROD', '1', '0,55', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 2255, '0', 1123),
(2024, ' 400 200 ECA RADYATÖR', '540', '0', '0', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 2487, '0', 1124),
(2025, ' ELEKTRİKLİ KOMBİ OMEGA 24 KW', '4.500,00', '3.398,40', '0', 'ADET', 20, 20, 'ELEKTRİKLİ KOMBİ', null, 'Evet', 2488, '1', 1125),
(2027, ' DAIKIN FWT06CAT DUVAR TİPİ FANCOİL', '4.400,00', '3.670,00', '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 2510, '1', 1127),
(2028, ' NEWTHERM FANCOİL-35 LİK', '3.300,00', '2.360,00', '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 2511, '1', 1128),
(2029, ' DAIKIN FANCOİL KUMANDASI', null, null, '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 2512, '1', 1129),
(2030, ' 1250 WALT NOBO ISITICI', '1.165,00', '776', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 2513, '0', 1130),
(2031, ' DAIKIN ISI POMPASI KUMANDASI', '4.500,00', '3.475,00', '2', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 2515, '0', 1131),
(2032, ' 25 WALT SANPA KARIŞTIRICI MOTORU', '3.500,00', '975', '49', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 2517, '20', 1132),
(2033, ' 40 WALT SANPA KARIŞTIRICI MOTORU', '4.500,00', '1.250,00', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 2518, '0', 1133),
(2034, ' 600 240 MAKTEK RADYATÖR', null, null, '0', 'MT', 20, 20, 'RADYATÖR', 'MAKTEK', 'Evet', 2519, '0', 1134),
(2035, ' 600 260 MAKTEK RADYATÖR', null, null, '0', 'MT', 20, 20, 'RADYATÖR', 'MAKTEK', 'Evet', 2520, '0', 1135),
(2036, ' 10 KW CHOFU ISI POMPASI', '15.000,00', null, '0', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 2521, '0', 1136),
(2038, ' 25 000 İMBİSAT ', '200', null, '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 2525, '0', 1138),
(2040, ' ALLVARİO 16/1 NEWTHERM ISI POMPASI', '16.950,00', '12.095,00', '0', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 2699, '0', 1140),
(2041, ' 500 LT ÇİFT SERPANTİNLİ BOYLER', '32.000,00', '24.200,00', '0', 'ADET', 20, 20, 'BOYLER', null, 'Evet', 2704, '0', 1141),
(2042, ' ETNA 3 KO 15/6-40 ÜÇ POMPALI DİK MİLLİ HİDROFOR', '15.900,00', '10.585,00', '0', 'ADET', 20, 20, 'HİDROFOR', null, 'Evet', 2705, '0', 1142),
(2043, ' ETNA 2 KO 10/7-30 İKİ POMPALI DİK MİLLİ HİDROFOR', '10.205,00', '6.805,00', '0', 'ADET', 20, 20, 'HİDROFOR', null, 'Evet', 2706, '0', 1143),
(2044, ' 1 1/4 DOĞALGAZ BORU BORUSAN PE KAPLI ', '46,44', '35,73', '0', 'MT', 20, 20, 'DOĞALGAZ BORUSU', null, 'Evet', 2736, '100', 1144),
(2045, ' 1 1/4 DOĞALGAZ BORU BORUSAN/ERBOSAN/ÇAYIROVA', '220', '170', '60', 'MT', 20, 20, 'DOĞALGAZ BORUSU', null, 'Evet', 2737, '100', 1145),
(2047, ' 600 70 CM ÜNMAK RADYATÖR ', '1.200,00', '915', '0', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 3632, '0', 1147),
(2049, ' 600 180 KALDE RADYATÖR', '3.200,00', '2.475,00', '0', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 3634, '0', 1149),
(2050, ' 900 130 ECA RADYATÖR ', '2.400,00', '2.000,00', '0', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 3635, '0', 1150),
(2051, ' PELET KAZANI KONTROL CİHAZI', '2.500,00', '1.530,00', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3636, '0', 1151),
(2052, ' 405M GÖVDE SİRKÜLASYON POMPASI', '4.600,00', '3.540,00', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3667, '0', 1152),
(2053, ' REHAU-343262-881 KOLLEKTÖR DOLABI SIVA ALTI TİP-1', '2.745,00', '2.115,00', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3668, '0', 1153),
(2054, ' REHAU-354893-881 KOLLEKTÖR DOLABI SIVA ALTI TİP-2', '3.290,00', '2.530,00', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3669, '0', 1154),
(2056, ' FERROLİ DİVACONDENS F24(20.000 KCAL/H) KOMBİ', '11.500,00', '8.700,00', '0', 'ADET', 20, 20, 'DOĞALGAZ KOMBİ', null, 'Evet', 3671, '2', 1156),
(2057, ' KONTROL KAPAĞI TEK CİDAR 32 MM İÇTEN VİDALI(MÜDAHALE KAPAĞI)', '430', '330', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3672, '0', 1157),
(2058, ' 500/1400 HAVLUPAN GOLD', '800', '600', '0', 'ADET', 20, 20, 'HAVLUPAN', null, 'Evet', 3673, '1', 1158),
(2060, ' 18.000 VESSEN KLİMA-50 BTU', '25.000,00', '19.059,00', '0', 'ADET', 20, 20, 'KLİMA', null, 'Evet', 3820, '1', 1160),
(2061, ' 1 SD 90/4 TR 1,5 KW HİDROFOR ', '16.000,00', '11.856,00', '0', 'ADET', 20, 20, 'HİDROFOR', null, 'Evet', 3821, '0', 1161),
(2026, ' 32 İSTAVROZ TE', '10', '8', '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 2489, '1', 1126),
(2037, ' Q 160 ISI İZOLELİ HAVA KANALI BORU', '190', '140', '0', 'KUTU', 20, 20, 'FİTTİNGS', null, 'Evet', 2524, '1', 1137),
(2039, ' TMV-S KABİN İÇİ TERMOSTAT-İMAS', '315', '225', '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 2698, '1', 1139),
(2046, ' PÜROMETRE 10 CM -250 DERECE', null, null, '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 2984, '0', 1146),
(2048, ' DN20 2 YOLLU DİŞLİ VANA', '568', '437', '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3633, '1', 1148),
(2055, ' 1/2 KROM UZATMA 4 CM ', '25', '19', '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3670, '1', 1155),
(2062, ' 1 1/4 ÇALPARALI ÇEKVALF', '315', '0', '1', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3822, '1', 1162),
(2111, ' 1/2 GALVANİZ BORU', '7,38', '5,67', '0', 'AD', 20, 20, 'FİTTİNGS', 'BORU', 'Evet', 412, '1', 1111),
(2112, ' 1 1/4 GALVANİZ BORU', '40', '26,83', '0', 'METRE', 20, 20, 'FİTTİNGS', 'BORU', 'Evet', 415, '0', 1112),
(2116, ' 1/2 KÖŞE RADYATÖR VANASI PEX-ÖZENİŞ/ORSEL', '130', '100', '14', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 2244, '1', 1116),
(2063, ' 9.000 LİK VESSEN KLİMA ', '13.000,00', '11.000,00', '0', 'ADET', 20, 20, 'KLİMA', null, 'Evet', 3824, '1', 1163),
(2064, ' WELKO Q63x2,5 B ALT.KURU MANOMETRE ', '300', '200', '20', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3825, '20', 1164),
(2065, ' BAYMAK 10 KW MONOBLOK ISI POMPASI', '120.000,00', '115.000,00', '0', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 3827, '0', 1165),
(2066, ' 16 KW SPLİT 230 LT BOYLER ENTEGRELİ DAIKIN ISI POMPASI ', '205.000,00', '180.000,00', '3', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 3838, '0', 1166),
(2067, ' 6 NO SALYANGOZ TİP 2,2 KW TRİFAZE 4.500 M3', '11.500,00', '8.700,00', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3839, '0', 1167),
(2068, ' 500/1200 KROM HAVLUPAN', '1.600,00', '1.250,00', '0', 'ADET', 20, 20, 'HAVLUPAN', null, 'Evet', 3840, '1', 1168),
(2070, ' 900 1000 COPA RADYATÖR', '3.300,00', '2.500,00', '0', 'ADET', 20, 20, 'RADYATÖR', 'COPA', 'Evet', 3842, '0', 1170),
(2071, ' 900 900 COPA RADYATÖR', '3.300,00', '2.500,00', '0', 'ADET', 20, 20, 'RADYATÖR', 'COPA', 'Evet', 3844, '0', 1171),
(2072, ' 8 KW BAYMAK MONOBLOK ISI POMPASI ', '92.000,00', '80.000,00', '0', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 3845, '0', 1172),
(2073, ' MOTORSUZ REDÜKTÖR 1/60 90-0,75 KW ŞANZIMAN', '6.100,00', '4.700,00', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3847, '0', 1173),
(2075, ' EVOSTA2 40-70/130 SİRKÜLASYON POMPASI', '5.500,00', '4.200,00', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3849, '0', 1111),
(2076, ' 22.000 DAİKİN SHİRA PLUS KLİMA', '61.000,00', '52.781,00', '0', 'ADET', 20, 20, 'KLİMA', null, 'Evet', 3851, '1', 1112),
(2077, ' 9.000 DAİKİN SHİRA PLUS KLİMA', '34.550,00', '30.039,00', '0', 'ADET', 20, 20, 'KLİMA', null, 'Evet', 3852, '1', 1113),
(2079, ' GÖZETLEME REKORU-SOMUN', '42', '32,5', '0', 'ADET', 20, 20, 'KAZAN MALZEMELERİ', null, 'Evet', 3854, '0', 1115),
(2080, ' AİRFEL AİRPO 10 KW ISI POMPASI MONOFAZE 3 KW ISITICILI', '136.033,00', '118.290,00', '3', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 3855, '0', 1116),
(2081, ' AİRFEL AİRPO 8 KW ISI POMPASI MONOFAZE 3 KW ISITICILI', '127.678,00', '111.025,00', '-2', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 3856, '0', 1117),
(2082, ' FWA03 GİZLİ TAVAN FCU2 BORULU FANCOİL SAĞ', '11.300,00', '8.695,00', '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 3868, '1', 1118),
(2083, ' FWA06 GİZLİ TAVAN FCU2 BORULU FANCOİL SAĞ', '14.720,00', '11.322,00', '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 3869, '1', 1119),
(2084, ' FWA05 GİZLİ TAVAN FCU2 BORULU FANCOİL SAĞ', '12.990,00', '9.993,00', '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 3870, '1', 1120),
(2086, ' REHAU 5 Lİ ÇELİK KOLLEKTÖR', '5.900,00', '4.550,00', '1', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3872, '0', 1122),
(2087, ' WARMHAUS ENERWAPLUS 33 KW KOMBİ', '20.500,00', '17.800,00', '0', 'ADET', 20, 20, 'DOĞALGAZ KOMBİ', null, 'Evet', 3873, '2', 1123),
(2088, ' 127 MM İZOLELİ FLEXBLE 10 MT', '890', '681', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3874, '0', 1124),
(2089, ' 102 MM İZOLELİ FLEXBLE 10 MT', '785', '602,5', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3875, '0', 1125),
(2090, ' AİRFEL DİGİFEL PREMİX 36 KW KOMBİ', '39.500,00', '31.200,00', '0', 'ADET', 20, 20, 'DOĞALGAZ KOMBİ', null, 'Evet', 3876, '2', 1126),
(2091, ' 1/2 ANTRASİT KÖŞE RADYATÖR VANASI', '420', '320', '3', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 3877, '48', 1127),
(2092, ' AİRFEL AİRPO 12 KW ISI POMPASI MONOFAZE 3 KW ISITICILI', '172.105,00', '149.656,00', '2', 'ADET', 20, 20, 'ISI POMPASI', null, 'Evet', 3878, '0', 1128),
(2093, ' 600 800-8 DİLİM ALÜMİNYUM RADYATÖR', '3.266,00', '2.512,00', '1', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 3879, '0', 1129),
(2094, ' 600 1200-12 DİLİM ALÜMİNYUM RADYATÖR', '6.485,00', '4.987,00', '0', 'ADET', 20, 20, 'RADYATÖR', null, 'Evet', 3880, '0', 1130),
(2095, ' 1000X500 ANTRASİT HAVLUPAN', '3.929,00', '3.022,00', '0', 'ADET', 20, 20, 'HAVLUPAN', null, 'Evet', 3881, '1', 1131),
(2096, ' KONTROL-SIEMENS-FC ODA TERMOSTATI-ODA TİPİ-SIVA ALTI', '1.480,00', '1.140,00', '1', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3882, '0', 1132),
(2097, ' DAIKIN PREMİX ICON 20 KW KOMBİ', '33.000,00', '28.670,00', '13', 'ADET', 20, 20, 'DOĞALGAZ KOMBİ', null, 'Evet', 3883, '2', 1133),
(2098, ' AİRFEL MAESTRO COMFORT PREMİX 28 KW KOMBİ', '37.250,00', '29.500,00', '0', 'ADET', 20, 20, 'DOĞALGAZ KOMBİ', null, 'Evet', 3902, '2', 1134),
(2101, ' SPS 100 MNF 0,75 KW POMPA', '8.750,00', '6.660,00', '0', 'ADET', 20, 20, 'HİDROFOR', null, 'Evet', 3915, '0', 1137),
(2102, ' ARMACELL KAUÇUK LEVHA İZOLE 6 MM KY(ŞİLTE)', '130', '95,75', '0', 'ADET', 20, 20, 'SATIŞ', null, 'Evet', 3917, '0', 1138),
(2103, ' KABLOSUZ MARS ODA TERMOSTADI S20 WİFİ ', '2.200,00', '1.700,00', '0', 'ADET', 20, 20, 'DOĞALGAZ', null, 'Evet', 3918, '10', 1139),
(2104, ' AİRFEL MAESTRO OPTİMUM PREMİX 20/24 KOMBİ', '29.000,00', '23.000,00', '0', 'ADET', 20, 20, 'DOĞALGAZ KOMBİ', null, 'Evet', 3919, '2', 1140),
(2105, ' U FANCOİL 2C ST RENK UNFC 080 YER TİPİ ÜNTES FANCOİL', '20.000,00', '16.000,00', '0', 'ADET', 20, 20, 'FANCOİL', null, 'Evet', 3920, '1', 1141),
(6666, 'Çelik sac', '45,00', '30,00', '12000', 'kg', 20, 20, 'Kalorifer kazanı', null, 'Evet', null, '5000', 1142),
(6671, 'Dökme demir', '35,00', '25,00', '9000', 'kg', 20, 20, 'Merkezi sistem ısıtma', null, 'Evet', null, null, 1147),
(6672, 'Plastik (PP/PVC)', '25,00', '15,00', '15000', 'kg', 20, 20, 'Klima sistemi', null, 'Evet', null, null, 1148),
(2069, ' 90 KAPAMA BAŞLIĞI', '288', '222', '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3841, '2', 1169),
(2078, ' 63X25X63 İNEGAL TE', '47,5', '36,5', '0', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3853, '1', 1114),
(2099, ' 75X50 REDÜKSİYON', '35', '27', '40', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3913, '0', 1135),
(2100, ' 75 TE', '105', '88', '30', 'ADET', 20, 20, 'FİTTİNGS', null, 'Evet', 3914, '0', 1136),
(6667, 'Paslanmaz çelik', '65,00', '50,00', '8500', 'kg', 20, 20, 'Kalorifer kazanı', null, 'Evet', null, '0', 1143),
(6668, 'Krom alaşım', '70,00', '55,00', '4200', 'kg', 20, 20, 'Yağ tankı', null, 'Evet', null, '0', 1144),
(6669, 'Alüminyum', '55,00', '40,00', '6800', 'kg', 20, 20, 'Isı pompası', null, 'Evet', null, '0', 1145),
(6670, 'Bakır boru', '120,00', '95,00', '3500', 'kg', 20, 20, 'Klima sistemi', null, 'Evet', null, '1', 1146),
(6673, 'Kauçuk conta', '40,00', '28,00', '2200', 'kg', 20, 20, 'Yağ tankı', null, 'Evet', null, null, 1149),
(6674, 'İzolasyon (Cam yünü)', '30,00', '20,00', '5600', 'kg', 20, 20, 'Isı pompası', null, 'Evet', null, null, 1150);
-- Part 3: Orders, Production, Recipes, Movements
-- TABLES: Urun_Recetesi, Siparis, Siparis_Maliyet, Uretim_Kayit, Hammadde_Hareket

-- 10. URUN RECETESI
INSERT INTO public.urun_recetesi (recete_id, urun_id, hammadde_id, miktar) VALUES
(4500, 3012, 2111, 5),
(4501, 3013, 2112, 5),
(4502, 3014, 2113, 5),
(4503, 3015, 2114, 5),
(4504, 3012, 2115, 5),
(4505, 3013, 2116, 5),
(4506, 3014, 2117, 5),
(4507, 3015, 2118, 5),
(4508, 3012, 2119, 5),
(4509, 3013, 2120, 5),
(4510, 3014, 2021, 5),
(4511, 3015, 2022, 5),
(4512, 3012, 2023, 5),
(4513, 3013, 2024, 5),
(4514, 3014, 2025, 5),
(4515, 3015, 2026, 5),
(4516, 3012, 2027, 5),
(4517, 3013, 2028, 5),
(4518, 3014, 2029, 5),
(4519, 3015, 2030, 5),
(4520, 3012, 2031, 5),
(4521, 3013, 2031, 5),
(4522, 3014, 2033, 5),
(4523, 3015, 2034, 5),
(4524, 3012, 2035, 5),
(4525, 3013, 2036, 5),
(4526, 3014, 2037, 5),
(4527, 3015, 2038, 5),
(4528, 3012, 2039, 5),
(4529, 3013, 2040, 5),
(4530, 3014, 2041, 5),
(4531, 3015, 2042, 5),
(4532, 3012, 2043, 5),
(4533, 3013, 2044, 5),
(4534, 3014, 2045, 5),
(4535, 3015, 2046, 5),
(4536, 3012, 2047, 5),
(4537, 3013, 2048, 5),
(4538, 3014, 2049, 5),
(4539, 3015, 2050, 5),
(4540, 3012, 2051, 5),
(4541, 3013, 2052, 5),
(4542, 3014, 2053, 5),
(4543, 3015, 2054, 5),
(4544, 3012, 2055, 5),
(4545, 3013, 2056, 5),
(4546, 3014, 2057, 5),
(4547, 3015, 2058, 5),
(4548, 3012, 2059, 5),
(4549, 3013, 2060, 5),
(4550, 3014, 2061, 5),
(4551, 3015, 2062, 5),
(4552, 3012, 2063, 5),
(4553, 3013, 2064, 5),
(4554, 3014, 2065, 5),
(4555, 3015, 2066, 5),
(4556, 3012, 2067, 5),
(4557, 3013, 2068, 5),
(4558, 3014, 2069, 5),
(4559, 3015, 2070, 5),
(4560, 3012, 2071, 5),
(4561, 3013, 2072, 5),
(4562, 3014, 2073, 5),
(4563, 3015, 2074, 5),
(4564, 3012, 2075, 5),
(4565, 3013, 2076, 5),
(4566, 3014, 2077, 5),
(4567, 3015, 2078, 5),
(4568, 3012, 2079, 5),
(4569, 3013, 2080, 5),
(4571, 3015, 2082, 5),
(4572, 3012, 2083, 5),
(4573, 3013, 2084, 5),
(4574, 3014, 2085, 5),
(4575, 3015, 2086, 5),
(4576, 3012, 2087, 5),
(4577, 3013, 2088, 5),
(4578, 3014, 2089, 5),
(4579, 3015, 2090, 5),
(4580, 3012, 2091, 5),
(4581, 3013, 2092, 5),
(4582, 3014, 2093, 5),
(4583, 3015, 2094, 5),
(4584, 3012, 2095, 5),
(4585, 3013, 2096, 5),
(4586, 3014, 2097, 5),
(4587, 3015, 2098, 5),
(4588, 3012, 2099, 5),
(4589, 3013, 2100, 5),
(4590, 3014, 2101, 5),
(4591, 3015, 2102, 5),
(4592, 3012, 2103, 5),
(4593, 3013, 2104, 5),
(4594, 3014, 2105, 5),
(4570, 3014, 2081, 5);

-- 11. SIPARIS
INSERT INTO public.siparis (siparis_id, musteri_id, siparis_tarihi, teslim_tarihi, durum, urun_id) VALUES
(7000, 8000, null, null, 'Beklemede', 3012),
(7001, 8001, null, null, 'Onayland', 3013),
(7003, 8003, null, null, 'Sevkiyatta', 3015),
(7004, 8004, null, null, 'Teslim edildi', 3016),
(7002, 8002, null, null, 'Hazırlanıyor', 3014);

-- 12. SIPARIS MALIYET
INSERT INTO public.siparis_maliyet (siparis_maliyet_id, siparis_id, hammadde_maliyeti, iscilik_maliyeti, toplam_maliyet, satis_fiyati, kar_zarar) VALUES
(8995, 7000, null, '10000', null, null, null),
(8996, 7001, null, '10000', null, null, null),
(8997, 7002, null, '10000', null, null, null),
(8998, 7003, null, '10000', null, null, null),
(8999, 7004, null, '10000', null, null, null);

-- 13. URETIM KAYIT
INSERT INTO public.uretim_kayit (uretim_id, urun_id, makine_id, baslama_zamani, bitis_zamani) VALUES
(5000, 3012, 5500, null, null),
(5001, 3013, 5501, null, null),
(5002, 3014, 5502, null, null),
(5003, 3015, 5503, null, null),
(5004, 3016, 5504, null, null),
(5005, 3012, 5505, null, null),
(5006, 3013, 5506, null, null),
(5007, 3014, 5507, null, null),
(5008, 3015, 5508, null, null),
(5009, 3016, 5509, null, null),
(5010, 3012, 5510, null, null),
(5011, 3013, 5511, null, null);

-- 14. HAMMADDE HAREKET
INSERT INTO public.hammadde_hareket (hareket_id, hammadde_id, hareket_turu, miktar, tarih) VALUES
(4100, 2111, 'giri', 20, null),
(4102, 2113, 'iade', 20, null),
(4109, 2120, 'iade', 20, null),
(4116, 2027, 'iade', 20, null),
(4123, 2034, 'iade', 20, null),
(4130, 2041, 'iade', 20, null),
(4137, 2048, 'iade', 20, null),
(4144, 2055, 'iade', 20, null),
(4151, 2062, 'iade', 20, null),
(4159, 2070, 'iade', 20, null),
(4166, 2077, 'iade', 20, null),
(4173, 2084, 'iade', 20, null),
(4180, 2091, 'iade', 20, null),
(4187, 2098, 'iade', 20, null),
(4194, 2105, 'iade', 20, null),
(4195, 6666, null, 20, null),
(4196, 6667, null, 20, null),
(4197, 6668, null, 20, null),
(4198, 6669, null, 20, null),
(4199, 6670, null, 20, null),
(4200, 6671, null, 20, null),
(4201, 6672, null, 20, null),
(4202, 6673, null, 20, null),
(4203, 6674, null, 20, null),
(4103, 2114, 'sayım fazla', 20, null),
(4118, 2029, 'sayım eksik', 20, null),
(4110, 2021, 'sayım fazla', 20, null),
(4188, 2099, 'sayım fazla', 20, null),
(4181, 2092, 'sayım fazla', 20, null),
(4174, 2085, 'sayım fazla', 20, null),
(4167, 2078, 'sayım fazla', 20, null),
(4160, 2071, 'sayım fazla', 20, null),
(4152, 2063, 'sayım fazla', 20, null),
(4145, 2056, 'sayım fazla', 20, null),
(4138, 2049, 'sayım fazla', 20, null),
(4131, 2042, 'sayım fazla', 20, null),
(4124, 2035, 'sayım fazla', 20, null),
(4117, 2028, 'sayım fazla', 20, null),
(4111, 2022, 'sayım eksik', 20, null),
(4104, 2115, 'sayım eksik', 20, null),
(4125, 2036, 'sayım eksik', 20, null),
(4132, 2043, 'sayım eksik', 20, null),
(4139, 2050, 'sayım eksik', 20, null),
(4146, 2057, 'sayım eksik', 20, null),
(4153, 2064, 'sayım eksik', 20, null),
(4161, 2072, 'sayım eksik', 20, null),
(4168, 2079, 'sayım eksik', 20, null),
(4175, 2086, 'sayım eksik', 20, null),
(4182, 2093, 'sayım eksik', 20, null),
(4189, 2100, 'sayım eksik', 20, null),
(4105, 2116, 'sipariş verildi', 20, null),
(4112, 2023, 'sipariş verildi', 20, null),
(4119, 2030, 'sipariş verildi', 20, null),
(4126, 2037, 'sipariş verildi', 20, null),
(4133, 2044, 'sipariş verildi', 20, null),
(4140, 2051, 'sipariş verildi', 20, null),
(4147, 2058, 'sipariş verildi', 20, null),
(4154, 2065, 'sipariş verildi', 20, null),
(4162, 2073, 'sipariş verildi', 20, null),
(4169, 2080, 'sipariş verildi', 20, null),
(4176, 2087, 'sipariş verildi', 20, null),
(4183, 2094, 'sipariş verildi', 20, null),
(4190, 2101, 'sipariş verildi', 20, null),
(4106, 2117, 'sipariş tamamlandı', 20, null),
(4113, 2024, 'sipariş tamamlandı', 20, null),
(4120, 2031, 'sipariş tamamlandı', 20, null),
(4127, 2038, 'sipariş tamamlandı', 20, null),
(4134, 2045, 'sipariş tamamlandı', 20, null),
(4141, 2052, 'sipariş tamamlandı', 20, null),
(4148, 2059, 'sipariş tamamlandı', 20, null),
(4155, 2066, 'sipariş tamamlandı', 20, null),
(4163, 2074, 'sipariş tamamlandı', 20, null),
(4170, 2081, 'sipariş tamamlandı', 20, null),
(4177, 2088, 'sipariş tamamlandı', 20, null),
(4184, 2095, 'sipariş tamamlandı', 20, null),
(4191, 2102, 'sipariş tamamlandı', 20, null),
(4101, 2112, 'erkek', 20, null),
(4108, 2119, 'erkek', 20, null),
(4115, 2026, 'erkek', 20, null),
(4122, 2033, 'erkek', 20, null),
(4129, 2040, 'erkek', 20, null),
(4136, 2047, 'erkek', 20, null),
(4143, 2054, 'erkek', 20, null),
(4150, 2061, 'erkek', 20, null),
(4158, 2069, 'erkek', 20, null),
(4165, 2076, 'erkek', 20, null),
(4172, 2083, 'erkek', 20, null),
(4179, 2090, 'erkek', 20, null),
(4186, 2097, 'erkek', 20, null),
(4193, 2104, 'erkek', 20, null),
(4107, 2118, 'giriş', 20, null),
(4114, 2025, 'giriş', 20, null),
(4121, 2032, 'giriş', 20, null);
- -   O E E   H e s a b � �   � � � � i n   G e r e k l i   S � � t u n l a r � �   E k l e m e  
 - -   E � xe r   s � � t u n l a r   z a t e n   v a r s a   h a t a   v e r m e z ,   y o k s a   e k l e r .  
  
 D O   $ $  
 B E G I N  
         - -   H e d e f   A d e t   ( P l a n s   o r   Q u o t a )  
         I F   N O T   E X I S T S   ( S E L E C T   1   F R O M   i n f o r m a t i o n _ s c h e m a . c o l u m n s   W H E R E   t a b l e _ n a m e   =   ' u r e t i m _ k a y i t '   A N D   c o l u m n _ n a m e   =   ' h e d e f _ a d e t ' )   T H E N  
                 A L T E R   T A B L E   p u b l i c . u r e t i m _ k a y i t   A D D   C O L U M N   h e d e f _ a d e t   i n t e g e r   D E F A U L T   0 ;  
         E N D   I F ;  
  
         - -   � Sr e t i l e n   A d e t   ( A c t u a l   O u t p u t )  
         I F   N O T   E X I S T S   ( S E L E C T   1   F R O M   i n f o r m a t i o n _ s c h e m a . c o l u m n s   W H E R E   t a b l e _ n a m e   =   ' u r e t i m _ k a y i t '   A N D   c o l u m n _ n a m e   =   ' u r e t i l e n _ a d e t ' )   T H E N  
                 A L T E R   T A B L E   p u b l i c . u r e t i m _ k a y i t   A D D   C O L U M N   u r e t i l e n _ a d e t   i n t e g e r   D E F A U L T   0 ;  
         E N D   I F ;  
  
         - -   F i r e   A d e t   ( R e j e c t s   /   S c r a p )  
         I F   N O T   E X I S T S   ( S E L E C T   1   F R O M   i n f o r m a t i o n _ s c h e m a . c o l u m n s   W H E R E   t a b l e _ n a m e   =   ' u r e t i m _ k a y i t '   A N D   c o l u m n _ n a m e   =   ' f i r e _ a d e t ' )   T H E N  
                 A L T E R   T A B L E   p u b l i c . u r e t i m _ k a y i t   A D D   C O L U M N   f i r e _ a d e t   i n t e g e r   D E F A U L T   0 ;  
         E N D   I F ;  
  
           - -   D u r u m   s � � t u n u   d a   e k s i k   o l a b i l i r  
         I F   N O T   E X I S T S   ( S E L E C T   1   F R O M   i n f o r m a t i o n _ s c h e m a . c o l u m n s   W H E R E   t a b l e _ n a m e   =   ' u r e t i m _ k a y i t '   A N D   c o l u m n _ n a m e   =   ' d u r u m ' )   T H E N  
                 A L T E R   T A B L E   p u b l i c . u r e t i m _ k a y i t   A D D   C O L U M N   d u r u m   t e x t ;  
         E N D   I F ;  
  
 E N D   $ $ ;  
  
 - -   U r e t i m   V e r i l e r i n i   T e m i z l e  
 T R U N C A T E   T A B L E   p u b l i c . u r e t i m _ k a y i t   R E S T A R T   I D E N T I T Y   C A S C A D E ;  
  
 - -   G e r � � e k � � i   � Sr e t i m   V e r i l e r i   ( S o n   7   G � � n   +   B u g � � n )  
 - -   M a k i n e   I D ' l e r i :   5 5 0 0 - 5 5 1 1  
 - -   � Sr � � n   I D ' l e r i :   3 0 1 2 - 3 0 1 6  
 - -   H e d e f   A d e t ,   � Sr e t i l e n   A d e t ,   F i r e   A d e t   d o l u  
  
 I N S E R T   I N T O   p u b l i c . u r e t i m _ k a y i t    
 ( u r e t i m _ i d ,   u r u n _ i d ,   m a k i n e _ i d ,   b a s l a m a _ z a m a n i ,   b i t i s _ z a m a n i ,   h e d e f _ a d e t ,   u r e t i l e n _ a d e t ,   f i r e _ a d e t )    
 V A L U E S  
 - -   T A M A M L A N A N L A R   ( G e � � m i � x  7   G � � n )  
 - -   G � � n   1   ( E s k i )  
 ( 5 0 0 1 ,   3 0 1 2 ,   5 5 0 0 ,   N O W ( )   -   I N T E R V A L   ' 7   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 7   d a y s '   +   I N T E R V A L   ' 6   h o u r s ' ,   1 0 0 ,   9 5 ,   2 ) ,   - -   � � y i   s k o r  
 ( 5 0 0 2 ,   3 0 1 3 ,   5 5 0 1 ,   N O W ( )   -   I N T E R V A L   ' 7   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 7   d a y s '   +   I N T E R V A L   ' 5   h o u r s ' ,   5 0 ,   4 0 ,   5 ) ,     - -   K � � t � �   s k o r  
 ( 5 0 0 3 ,   3 0 1 4 ,   5 5 0 2 ,   N O W ( )   -   I N T E R V A L   ' 6   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 6   d a y s '   +   I N T E R V A L   ' 8   h o u r s ' ,   2 0 0 ,   1 9 8 ,   1 ) ,  
  
 - -   G � � n   2  
 ( 5 0 0 4 ,   3 0 1 5 ,   5 5 0 3 ,   N O W ( )   -   I N T E R V A L   ' 5   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 5   d a y s '   +   I N T E R V A L   ' 7   h o u r s ' ,   8 0 ,   7 5 ,   0 ) ,  
 ( 5 0 0 5 ,   3 0 1 6 ,   5 5 0 4 ,   N O W ( )   -   I N T E R V A L   ' 5   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 5   d a y s '   +   I N T E R V A L   ' 4   h o u r s ' ,   4 0 ,   3 8 ,   1 ) ,  
 ( 5 0 0 6 ,   3 0 1 2 ,   5 5 0 5 ,   N O W ( )   -   I N T E R V A L   ' 5   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 5   d a y s '   +   I N T E R V A L   ' 6   h o u r s ' ,   1 2 0 ,   1 1 0 ,   8 ) ,  
  
 - -   G � � n   3  
 ( 5 0 0 7 ,   3 0 1 3 ,   5 5 0 6 ,   N O W ( )   -   I N T E R V A L   ' 4   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 4   d a y s '   +   I N T E R V A L   ' 5   h o u r s ' ,   6 0 ,   6 0 ,   0 ) ,   - -   % 1 0 0   P e r f  
 ( 5 0 0 8 ,   3 0 1 4 ,   5 5 0 7 ,   N O W ( )   -   I N T E R V A L   ' 4   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 4   d a y s '   +   I N T E R V A L   ' 8   h o u r s ' ,   1 5 0 ,   1 3 0 ,   1 0 ) ,  
 ( 5 0 0 9 ,   3 0 1 5 ,   5 5 0 8 ,   N O W ( )   -   I N T E R V A L   ' 4   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 4   d a y s '   +   I N T E R V A L   ' 3   h o u r s ' ,   4 0 ,   3 5 ,   2 ) ,  
  
 - -   G � � n   4  
 ( 5 0 1 0 ,   3 0 1 6 ,   5 5 0 9 ,   N O W ( )   -   I N T E R V A L   ' 3   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 3   d a y s '   +   I N T E R V A L   ' 9   h o u r s ' ,   5 0 ,   4 8 ,   1 ) ,  
 ( 5 0 1 1 ,   3 0 1 2 ,   5 5 1 0 ,   N O W ( )   -   I N T E R V A L   ' 3   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 3   d a y s '   +   I N T E R V A L   ' 6   h o u r s ' ,   9 0 ,   8 5 ,   3 ) ,  
  
 - -   G � � n   5  
 ( 5 0 1 2 ,   3 0 1 3 ,   5 5 0 0 ,   N O W ( )   -   I N T E R V A L   ' 2   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 2   d a y s '   +   I N T E R V A L   ' 7   h o u r s ' ,   7 0 ,   6 8 ,   0 ) ,  
 ( 5 0 1 3 ,   3 0 1 4 ,   5 5 0 1 ,   N O W ( )   -   I N T E R V A L   ' 2   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 2   d a y s '   +   I N T E R V A L   ' 5   h o u r s ' ,   1 1 0 ,   9 0 ,   1 5 ) ,   - -   Y � � k s e k   f i r e  
 ( 5 0 1 4 ,   3 0 1 5 ,   5 5 0 2 ,   N O W ( )   -   I N T E R V A L   ' 2   d a y s ' ,   N O W ( )   -   I N T E R V A L   ' 2   d a y s '   +   I N T E R V A L   ' 8   h o u r s ' ,   1 0 0 ,   9 9 ,   1 ) ,  
  
 - -   G � � n   6   ( D � � n )  
 ( 5 0 1 5 ,   3 0 1 6 ,   5 5 0 3 ,   N O W ( )   -   I N T E R V A L   ' 1   d a y ' ,   N O W ( )   -   I N T E R V A L   ' 1   d a y '   +   I N T E R V A L   ' 6   h o u r s ' ,   6 0 ,   5 8 ,   2 ) ,  
 ( 5 0 1 6 ,   3 0 1 2 ,   5 5 0 4 ,   N O W ( )   -   I N T E R V A L   ' 1   d a y ' ,   N O W ( )   -   I N T E R V A L   ' 1   d a y '   +   I N T E R V A L   ' 4   h o u r s ' ,   8 5 ,   8 0 ,   0 ) ,  
 ( 5 0 1 7 ,   3 0 1 3 ,   5 5 0 5 ,   N O W ( )   -   I N T E R V A L   ' 1   d a y ' ,   N O W ( )   -   I N T E R V A L   ' 1   d a y '   +   I N T E R V A L   ' 7   h o u r s ' ,   1 3 0 ,   1 0 0 ,   5 ) ,  
  
 - -   D E V A M   E D E N L E R   ( B u g � � n )  
 - -   B i t i s   z a m a n � �   N U L L  
 ( 5 0 1 8 ,   3 0 1 4 ,   5 5 0 0 ,   N O W ( )   -   I N T E R V A L   ' 2   h o u r s ' ,   N U L L ,   1 5 0 ,   3 0 ,   0 ) ,       - -   Y e n i   b a � xl a d � �  
 ( 5 0 1 9 ,   3 0 1 5 ,   5 5 0 1 ,   N O W ( )   -   I N T E R V A L   ' 4   h o u r s ' ,   N U L L ,   8 0 ,   4 5 ,   1 ) ,         - -   O r t a d a  
 ( 5 0 2 0 ,   3 0 1 6 ,   5 5 0 2 ,   N O W ( )   -   I N T E R V A L   ' 1   h o u r s ' ,   N U L L ,   5 0 ,   1 0 ,   0 ) ,         - -   Y e n i  
 ( 5 0 2 1 ,   3 0 1 2 ,   5 5 0 6 ,   N O W ( )   -   I N T E R V A L   ' 5   h o u r s ' ,   N U L L ,   2 0 0 ,   1 2 0 ,   3 ) ,     - -   � � l e r l e d i  
 ( 5 0 2 2 ,   3 0 1 3 ,   5 5 0 7 ,   N O W ( )   -   I N T E R V A L   ' 3 0   m i n u t e s ' ,   N U L L ,   1 0 0 ,   5 ,   0 ) ;   - -   � ! o k   y e n i  
  
 - -   S e q u e n c e   U p d a t e  
 S E L E C T   s e t v a l ( ' u r e t i m _ k a y i t _ u r e t i m _ i d _ s e q ' ,   ( S E L E C T   M A X ( u r e t i m _ i d )   F R O M   u r e t i m _ k a y i t ) ) ;  
 