-- Bu scripti Supabase SQL Editor'de çalıştırarak uretim_id sütununun otomatik artmasını sağlayabilirsiniz.
-- Eğer tablo zaten identity ise hata verebilir, bu durumda görmezden gelebilirsiniz veya scripti çalıştırıp sonucu kontrol edebilirsiniz.

-- 1. uretim_kayit tablosundaki uretim_id sütununu otomatik artan (Identity) yap
-- Not: Eğer "column already has a default value" hatası alırsanız, bu adımı atlayabilirsiniz.
ALTER TABLE uretim_kayit ALTER COLUMN uretim_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Sequence'i mevcut en büyük ID'ye eşitle (böylece çakışma olmaz)
SELECT setval(pg_get_serial_sequence('uretim_kayit', 'uretim_id'), (SELECT COALESCE(MAX(uretim_id), 0) + 1 FROM uretim_kayit), false);

-- Diğer tablolar için de benzer işlem yapılabilir (ihtiyaç olursa):
-- ALTER TABLE siparis_maliyet ALTER COLUMN siparis_maliyet_id ADD GENERATED BY DEFAULT AS IDENTITY;
-- SELECT setval(pg_get_serial_sequence('siparis_maliyet', 'siparis_maliyet_id'), (SELECT COALESCE(MAX(siparis_maliyet_id), 0) + 1 FROM siparis_maliyet), false);
